-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "public"."fail_mode" AS ENUM('Ticketed', 'Resolved Immediately');--> statement-breakpoint
CREATE TYPE "public"."qc_status" AS ENUM('na', 'pass', 'fail');--> statement-breakpoint
CREATE TYPE "public"."waited_reason" AS ENUM('Faculty Noncompliance');--> statement-breakpoint
CREATE TABLE "faculty_setup" (
	"faculty" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "faculty_setup_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"uses_mic" boolean,
	"left_source" text,
	"right_source" text,
	"updated_at" timestamp with time zone,
	"mirroring360" boolean,
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text,
	"notes" text,
	"left_device" text,
	"right_device" text,
	CONSTRAINT "faculty_setup_id_key" UNIQUE("id")
);
--> statement-breakpoint
ALTER TABLE "faculty_setup" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "event_hybrid" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"event" bigint PRIMARY KEY NOT NULL,
	"config" text,
	"meeting_id" bigint,
	"meeting_link" text,
	"instructions" text,
	"source" text
);
--> statement-breakpoint
ALTER TABLE "event_hybrid" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "qc_item_dict" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "qc_item_def_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"display_name" text NOT NULL,
	"instruction" text NOT NULL,
	"icon" text
);
--> statement-breakpoint
ALTER TABLE "qc_item_dict" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "event_av_config" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"event" bigint PRIMARY KEY NOT NULL,
	"left_source" text,
	"right_source" text,
	"left_device" text,
	"right_device" text,
	"handhelds" integer DEFAULT 0 NOT NULL,
	"lapels" integer DEFAULT 0 NOT NULL,
	"clicker" boolean,
	"center_source" text,
	"center_device" text
);
--> statement-breakpoint
ALTER TABLE "event_av_config" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "event_recording" (
	"event" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_recording_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"instructions" text,
	"type" text
);
--> statement-breakpoint
ALTER TABLE "event_recording" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "actions" (
	"id" bigint PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"event" bigint,
	"type" text NOT NULL,
	"start_time" time NOT NULL,
	"status" text NOT NULL,
	"assigned_to" uuid,
	"completed_by" uuid,
	"completed_time" timestamp with time zone,
	"sub_type" text,
	"source" text
);
--> statement-breakpoint
ALTER TABLE "actions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "academic_calendar" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "academic_calendar_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"label" text,
	"date" timestamp with time zone,
	"date_string" text,
	"start_of_quarter" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
ALTER TABLE "academic_calendar" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "organizations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "clubs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" text,
	"logo" text,
	"about" text,
	"url" text
);
--> statement-breakpoint
ALTER TABLE "organizations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "faculty" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "faculty_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"kelloggdirectory_name" text,
	"twentyfivelive_name" text,
	"kelloggdirectory_title" text,
	"kelloggdirectory_bio" text,
	"kelloggdirectory_image_url" text,
	"updated_at" timestamp,
	"kelloggdirectory_bio_url" text,
	"kelloggdirectory_subtitle" text,
	"cutout_image" text,
	CONSTRAINT "faculty_kelloggdirectory_name_key" UNIQUE("kelloggdirectory_name")
);
--> statement-breakpoint
ALTER TABLE "faculty" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid,
	"title" text NOT NULL,
	"message" text NOT NULL,
	"type" text NOT NULL,
	"event_id" bigint,
	"read_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now(),
	"data" jsonb
);
--> statement-breakpoint
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "faculty_updates" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "faculty_updates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"faculty" bigint,
	"author" uuid DEFAULT gen_random_uuid(),
	"content" text,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "faculty_updates" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "rooms" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rooms_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" text NOT NULL,
	"spelling" text,
	"type" text DEFAULT 'CLASSROOM',
	"sub_type" text DEFAULT 'TIERED'
);
--> statement-breakpoint
ALTER TABLE "rooms" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "profiles" (
	"id" uuid PRIMARY KEY NOT NULL,
	"name" text,
	"auto_hide" boolean DEFAULT false NOT NULL,
	"current_filter" text,
	"bg" text,
	"roles" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"theme" text DEFAULT 'dark' NOT NULL,
	"color" text,
	"zoom" real,
	"pixels_per_min" double precision,
	"row_height" bigint,
	"start_hour" bigint,
	"end_hour" bigint,
	CONSTRAINT "check_roles_is_array" CHECK (jsonb_typeof(roles) = 'array'::text)
);
--> statement-breakpoint
ALTER TABLE "profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "room_filters" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "room_filters_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" text,
	"display" jsonb
);
--> statement-breakpoint
ALTER TABLE "room_filters" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "series" (
	"id" bigint PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"series_name" text NOT NULL,
	"series_type" text NOT NULL,
	"total_events" integer NOT NULL,
	"first_date" date NOT NULL,
	"last_date" date NOT NULL
);
--> statement-breakpoint
ALTER TABLE "series" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "resources_dict" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text,
	"is_av" boolean,
	"icon" jsonb,
	CONSTRAINT "resources_id_key" UNIQUE("id")
);
--> statement-breakpoint
ALTER TABLE "resources_dict" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "shift_blocks" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shift_blocks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"assignments" jsonb,
	"start_time" time,
	"end_time" time,
	"date" date
);
--> statement-breakpoint
ALTER TABLE "shift_blocks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "events" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"event_type" text,
	"lecture_title" text,
	"room_name" text NOT NULL,
	"resources" jsonb DEFAULT '[]'::jsonb,
	"id" bigint PRIMARY KEY NOT NULL,
	"item_id2" bigint,
	"start_time" time NOT NULL,
	"end_time" time NOT NULL,
	"raw" jsonb,
	"item_id" bigint,
	"event_name" text NOT NULL,
	"updated_at" timestamp with time zone,
	"man_owner" uuid,
	"date" date NOT NULL,
	"instructor_names" jsonb,
	"organization" text,
	"transform" text,
	"series_pos" bigint,
	"series" bigint,
	CONSTRAINT "instructor_name_is_array_or_null" CHECK ((instructor_names IS NULL) OR (jsonb_typeof(instructor_names) = 'array'::text))
);
--> statement-breakpoint
ALTER TABLE "events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "panopto_checks" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"event_id" bigint NOT NULL,
	"check_time" time NOT NULL,
	"completed_time" time,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now(),
	"completed_by_user_id" uuid,
	"status" text
);
--> statement-breakpoint
ALTER TABLE "panopto_checks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "shifts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shifts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"profile_id" uuid,
	"start_time" time,
	"end_time" time,
	"date" date
);
--> statement-breakpoint
ALTER TABLE "shifts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "other_hardware_dict" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"id" text PRIMARY KEY NOT NULL,
	CONSTRAINT "other_hardware_dict_id_key" UNIQUE("id")
);
--> statement-breakpoint
ALTER TABLE "other_hardware_dict" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "faculty_events" (
	"faculty" bigint NOT NULL,
	"event" bigint NOT NULL,
	CONSTRAINT "faculty_events_pkey" PRIMARY KEY("faculty","event")
);
--> statement-breakpoint
ALTER TABLE "faculty_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "shift_block_profile_room" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"room" bigint NOT NULL,
	"profile" uuid NOT NULL,
	"shift_block" bigint NOT NULL,
	CONSTRAINT "shift_block_profile_room_pkey" PRIMARY KEY("room","profile","shift_block")
);
--> statement-breakpoint
ALTER TABLE "shift_block_profile_room" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "resource_events" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"resource_id" text NOT NULL,
	"event_id" bigint NOT NULL,
	"quantity" integer DEFAULT 1 NOT NULL,
	"instructions" text,
	CONSTRAINT "resource_events_pkey" PRIMARY KEY("resource_id","event_id")
);
--> statement-breakpoint
CREATE TABLE "event_other_hardware" (
	"event" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "event_external_hardware_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"quantity" integer,
	"instructions" text,
	"other_hardware_dict" text NOT NULL,
	CONSTRAINT "event_other_hardware_pkey" PRIMARY KEY("event","other_hardware_dict")
);
--> statement-breakpoint
ALTER TABLE "event_other_hardware" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "qc_items" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"action" bigint NOT NULL,
	"qc_item_dict" bigint NOT NULL,
	"sn_ticket" text,
	"waived" boolean,
	"waived_reason" "waited_reason",
	"fail_mode" "fail_mode",
	"status" "qc_status",
	CONSTRAINT "qc_items_pk" PRIMARY KEY("action","qc_item_dict")
);
--> statement-breakpoint
ALTER TABLE "qc_items" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "faculty_setup" ADD CONSTRAINT "faculty_setup_faculty_fkey" FOREIGN KEY ("faculty") REFERENCES "public"."faculty"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_hybrid" ADD CONSTRAINT "event_hybrid_event_fkey" FOREIGN KEY ("event") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_av_config" ADD CONSTRAINT "event_av_config_event_fkey" FOREIGN KEY ("event") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_recording" ADD CONSTRAINT "event_recording_event_fkey" FOREIGN KEY ("event") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "actions" ADD CONSTRAINT "actions_assigned_to_fkey" FOREIGN KEY ("assigned_to") REFERENCES "public"."profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "actions" ADD CONSTRAINT "actions_completed_by_fkey" FOREIGN KEY ("completed_by") REFERENCES "public"."profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "actions" ADD CONSTRAINT "actions_event_fkey" FOREIGN KEY ("event") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey1" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_man_owner_fkey" FOREIGN KEY ("man_owner") REFERENCES "public"."profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_series_fkey" FOREIGN KEY ("series") REFERENCES "public"."series"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "panopto_checks" ADD CONSTRAINT "panopto_checks_completed_by_user_id_fkey" FOREIGN KEY ("completed_by_user_id") REFERENCES "public"."profiles"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "panopto_checks" ADD CONSTRAINT "panopto_checks_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shifts" ADD CONSTRAINT "shifts_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "faculty_events" ADD CONSTRAINT "faculty_events_event_fkey" FOREIGN KEY ("event") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "faculty_events" ADD CONSTRAINT "faculty_events_faculty_fkey" FOREIGN KEY ("faculty") REFERENCES "public"."faculty"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shift_block_profile_room" ADD CONSTRAINT "shift_block_profile_room_profile_fkey" FOREIGN KEY ("profile") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shift_block_profile_room" ADD CONSTRAINT "shift_block_profile_room_room_fkey" FOREIGN KEY ("room") REFERENCES "public"."rooms"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shift_block_profile_room" ADD CONSTRAINT "shift_block_profile_room_shift_block_fkey" FOREIGN KEY ("shift_block") REFERENCES "public"."shift_blocks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_events" ADD CONSTRAINT "fk_event" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_events" ADD CONSTRAINT "fk_resource" FOREIGN KEY ("resource_id") REFERENCES "public"."resources_dict"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_other_hardware" ADD CONSTRAINT "event_other_hardware_event_fkey" FOREIGN KEY ("event") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_other_hardware" ADD CONSTRAINT "event_other_hardware_other_hardware_dict_fkey" FOREIGN KEY ("other_hardware_dict") REFERENCES "public"."other_hardware_dict"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qc_items" ADD CONSTRAINT "qc_item_qc_item_dict_fkey" FOREIGN KEY ("qc_item_dict") REFERENCES "public"."qc_item_dict"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qc_items" ADD CONSTRAINT "qc_items_action_fkey" FOREIGN KEY ("action") REFERENCES "public"."actions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_profiles_name" ON "profiles" USING btree ("name" text_ops);--> statement-breakpoint
CREATE INDEX "idx_profiles_roles" ON "profiles" USING gin ("roles" jsonb_ops);--> statement-breakpoint
CREATE INDEX "idx_events_date_start_time" ON "events" USING btree ("date" date_ops,"start_time" date_ops);--> statement-breakpoint
CREATE INDEX "idx_events_event_name_start_time" ON "events" USING btree ("event_name" text_ops,"start_time" text_ops);--> statement-breakpoint
CREATE INDEX "idx_events_event_type" ON "events" USING btree ("event_type" text_ops);--> statement-breakpoint
CREATE INDEX "idx_events_id" ON "events" USING btree ("id" int8_ops);--> statement-breakpoint
CREATE INDEX "idx_events_room_name" ON "events" USING btree ("room_name" text_ops);--> statement-breakpoint
CREATE INDEX "idx_events_start_time" ON "events" USING btree ("start_time" time_ops);--> statement-breakpoint
CREATE POLICY "allow all to authenticated" ON "faculty_setup" AS PERMISSIVE FOR ALL TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "Allow all to authenticated" ON "academic_calendar" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Policy with security definer functions" ON "organizations" AS PERMISSIVE FOR ALL TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "Allow all to authenticated" ON "faculty" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Allow all to authenticated" ON "notifications" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "notifications_select_own" ON "notifications" AS PERMISSIVE FOR SELECT TO "authenticated";--> statement-breakpoint
CREATE POLICY "rt_select_all_notifications" ON "notifications" AS PERMISSIVE FOR SELECT TO "anon", "authenticated";--> statement-breakpoint
CREATE POLICY "Allow all to authenticated" ON "faculty_updates" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Allow all to authenticated" ON "rooms" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Allow all to authenticated" ON "profiles" AS PERMISSIVE FOR ALL TO "anon", "authenticated" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Allow all to authenticated" ON "room_filters" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Allow all to authenticated" ON "shift_blocks" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Allow all to authenticated" ON "events" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Allow all to authenticated" ON "panopto_checks" AS PERMISSIVE FOR ALL TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "Allow all to authenticated" ON "shifts" AS PERMISSIVE FOR ALL TO "authenticated" USING (true) WITH CHECK (true);
*/