CREATE TYPE "public"."fail_mode" AS ENUM('Ticketed', 'Resolved Immediately');--> statement-breakpoint
CREATE TYPE "public"."qc_status" AS ENUM('na', 'pass', 'fail');--> statement-breakpoint
CREATE TYPE "public"."waited_reason" AS ENUM('Faculty Noncompliance');--> statement-breakpoint
CREATE TABLE "actions" (
	"id" bigint PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"event" bigint,
	"type" text NOT NULL,
	"start_time" time NOT NULL,
	"status" text NOT NULL,
	"assigned_to" uuid,
	"completed_by" uuid,
	"completed_time" timestamp with time zone,
	"sub_type" text,
	"source" text
);
--> statement-breakpoint
CREATE TABLE "event_av_config" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"event" bigint PRIMARY KEY NOT NULL,
	"left_source" text,
	"right_source" text,
	"left_device" text,
	"right_device" text,
	"handhelds" integer DEFAULT 0 NOT NULL,
	"lapels" integer DEFAULT 0 NOT NULL,
	"clicker" boolean,
	"center_source" text,
	"center_device" text
);
--> statement-breakpoint
CREATE TABLE "event_hybrid" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"event" bigint PRIMARY KEY NOT NULL,
	"config" text,
	"meeting_id" bigint,
	"meeting_link" text,
	"instructions" text,
	"source" text
);
--> statement-breakpoint
CREATE TABLE "event_other_hardware" (
	"event" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "event_external_hardware_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"quantity" integer,
	"instructions" text,
	"other_hardware_dict" text NOT NULL,
	CONSTRAINT "event_other_hardware_pkey" PRIMARY KEY("event","other_hardware_dict")
);
--> statement-breakpoint
CREATE TABLE "event_recording" (
	"event" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_recording_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"instructions" text,
	"type" text
);
--> statement-breakpoint
CREATE TABLE "faculty_events" (
	"faculty" bigint NOT NULL,
	"event" bigint NOT NULL,
	CONSTRAINT "faculty_events_pkey" PRIMARY KEY("faculty","event")
);
--> statement-breakpoint
CREATE TABLE "faculty_setup" (
	"faculty" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "faculty_setup_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"uses_mic" boolean,
	"left_source" text,
	"right_source" text,
	"updated_at" timestamp with time zone,
	"mirroring360" boolean,
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text,
	"notes" text,
	"left_device" text,
	"right_device" text,
	CONSTRAINT "faculty_setup_id_key" UNIQUE("id")
);
--> statement-breakpoint
ALTER TABLE "faculty_setup" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "other_hardware_dict" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"id" text PRIMARY KEY NOT NULL,
	CONSTRAINT "other_hardware_dict_id_key" UNIQUE("id")
);
--> statement-breakpoint
CREATE TABLE "qc_item_dict" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "qc_item_def_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854776000 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"display_name" text NOT NULL,
	"instruction" text NOT NULL,
	"icon" text
);
--> statement-breakpoint
CREATE TABLE "qc_items" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"action" bigint NOT NULL,
	"qc_item_dict" bigint NOT NULL,
	"sn_ticket" text,
	"waived" boolean,
	"waived_reason" "waited_reason",
	"fail_mode" "fail_mode",
	"status" "qc_status",
	CONSTRAINT "qc_items_pk" PRIMARY KEY("action","qc_item_dict")
);
--> statement-breakpoint
CREATE TABLE "resource_events" (
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"resource_id" text NOT NULL,
	"event_id" bigint NOT NULL,
	"quantity" integer DEFAULT 1 NOT NULL,
	"instructions" text,
	CONSTRAINT "resource_events_pkey" PRIMARY KEY("resource_id","event_id")
);
--> statement-breakpoint
CREATE TABLE "resources_dict" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text,
	"is_av" boolean,
	"icon" jsonb,
	CONSTRAINT "resources_id_key" UNIQUE("id")
);
--> statement-breakpoint
ALTER TABLE "organizations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "panopto_checks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "notifications" DROP CONSTRAINT "notifications_user_id_fkey";
--> statement-breakpoint
DROP INDEX "idx_events_end_time";--> statement-breakpoint
DROP INDEX "idx_events_item_id";--> statement-breakpoint
DROP INDEX "idx_events_item_id2";--> statement-breakpoint
DROP INDEX "idx_events_date_start_time";--> statement-breakpoint
DROP INDEX "idx_events_event_name_start_time";--> statement-breakpoint
ALTER TABLE "shift_blocks" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "academic_calendar" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "rooms" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "rooms" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "room_name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "id" DROP IDENTITY;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "start_time" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "end_time" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "event_name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "events" ALTER COLUMN "date" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "faculty_updates" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "faculty" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "organizations" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "shifts" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "room_filters" ALTER COLUMN "id" SET MAXVALUE 9223372036854776000;--> statement-breakpoint
ALTER TABLE "rooms" ADD COLUMN "type" text DEFAULT 'CLASSROOM';--> statement-breakpoint
ALTER TABLE "rooms" ADD COLUMN "sub_type" text DEFAULT 'TIERED';--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "firstLecture" boolean;--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "transform" text;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "theme" text DEFAULT 'dark' NOT NULL;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "color" text;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "zoom" real;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "pixels_per_min" double precision;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "row_height" bigint;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "start_hour" bigint;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "end_hour" bigint;--> statement-breakpoint
ALTER TABLE "actions" ADD CONSTRAINT "actions_assigned_to_fkey" FOREIGN KEY ("assigned_to") REFERENCES "public"."profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "actions" ADD CONSTRAINT "actions_completed_by_fkey" FOREIGN KEY ("completed_by") REFERENCES "public"."profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "actions" ADD CONSTRAINT "actions_event_fkey" FOREIGN KEY ("event") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_av_config" ADD CONSTRAINT "event_av_config_event_fkey" FOREIGN KEY ("event") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_hybrid" ADD CONSTRAINT "event_hybrid_event_fkey" FOREIGN KEY ("event") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_other_hardware" ADD CONSTRAINT "event_other_hardware_event_fkey" FOREIGN KEY ("event") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_other_hardware" ADD CONSTRAINT "event_other_hardware_other_hardware_dict_fkey" FOREIGN KEY ("other_hardware_dict") REFERENCES "public"."other_hardware_dict"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event_recording" ADD CONSTRAINT "event_recording_event_fkey" FOREIGN KEY ("event") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "faculty_events" ADD CONSTRAINT "faculty_events_event_fkey" FOREIGN KEY ("event") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "faculty_events" ADD CONSTRAINT "faculty_events_faculty_fkey" FOREIGN KEY ("faculty") REFERENCES "public"."faculty"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "faculty_setup" ADD CONSTRAINT "faculty_setup_faculty_fkey" FOREIGN KEY ("faculty") REFERENCES "public"."faculty"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qc_items" ADD CONSTRAINT "qc_item_qc_item_dict_fkey" FOREIGN KEY ("qc_item_dict") REFERENCES "public"."qc_item_dict"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qc_items" ADD CONSTRAINT "qc_items_action_fkey" FOREIGN KEY ("action") REFERENCES "public"."actions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_events" ADD CONSTRAINT "fk_event" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_events" ADD CONSTRAINT "fk_resource" FOREIGN KEY ("resource_id") REFERENCES "public"."resources_dict"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_fkey1" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_events_date_start_time" ON "events" USING btree ("date" date_ops,"start_time" date_ops);--> statement-breakpoint
CREATE INDEX "idx_events_event_name_start_time" ON "events" USING btree ("event_name" text_ops,"start_time" text_ops);--> statement-breakpoint
ALTER TABLE "faculty" DROP COLUMN "timing";--> statement-breakpoint
ALTER TABLE "faculty" DROP COLUMN "complexity";--> statement-breakpoint
ALTER TABLE "faculty" DROP COLUMN "temperment";--> statement-breakpoint
ALTER TABLE "faculty" DROP COLUMN "uses_mic";--> statement-breakpoint
ALTER TABLE "faculty" DROP COLUMN "left_source";--> statement-breakpoint
ALTER TABLE "faculty" DROP COLUMN "right_source";--> statement-breakpoint
ALTER TABLE "faculty" DROP COLUMN "setup_notes";--> statement-breakpoint
ALTER TABLE "room_filters" DROP COLUMN "owner";--> statement-breakpoint
ALTER TABLE "room_filters" DROP COLUMN "default";--> statement-breakpoint
CREATE POLICY "Policy with security definer functions" ON "organizations" AS PERMISSIVE FOR ALL TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "Allow all to authenticated" ON "panopto_checks" AS PERMISSIVE FOR ALL TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "allow all to authenticated" ON "faculty_setup" AS PERMISSIVE FOR ALL TO "authenticated" USING (true);--> statement-breakpoint
ALTER POLICY "Allow all to authenticated" ON "profiles" TO anon,authenticated USING (true) WITH CHECK (true);